# Welcome to serverless. Read the docs
# https://serverless.com/framework/docs/

# Serverless.yml is the configuration the CLI
# uses to deploy your code to your provider of choice

# This serverless.yml file deploys content in the /static folder to
# an S3 bucket which will host the frontend static web content

# The `service` block is the name of the service
service: zach-manno-io

frameworkVersion: '3'

# The `provider` block defines where your service will be deployed
provider:
  name: aws
  runtime: nodejs12.x

resources:
  Resources:
    StaticSite:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.siteName}
    StaticSiteS3BucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket:
          Ref: StaticSite
        PolicyDocument:
          Statement:
            - Sid: CloudfrontGetObject
              Effect: Allow
              Principal:
                CanonicalUser:
                  - '603adfc78c0d71f9d01c7f20d02bb5ae06f6fbfaf41a889411aa84347af41159d975303e279482e469aff931ce721534'
              Action:
                - s3:GetObject
              Resource:
                Fn::Join: [
                    "", [
                      "arn:aws:s3:::",
                    {
                      "Ref": "StaticSite"
                    },
                      "/*"
                  ]
                ]

plugins:
  - serverless-s3-sync

custom:
  siteName: zachmanno.io
  s3Sync:
    - bucketName: ${self:custom.siteName}
      localDir: static
