AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  WeatherFunction:
    Type: AWS::Serverless::Function
    Properties:
      MemorySize: 128
      Architectures: ["arm64"]
      Handler: bootstrap
      Runtime: provided.al2
      Timeout: 5
      CodeUri: build/
      Events:
        Api:
          Type: HttpApi
          Api:
            Cors:
              AllowMethods: "'GET,POST,OPTIONS'"
              AllowHeaders: "'content-type'"
              AllowOrigin: "'*'"
              AllowCredentials: "'*'"
          Properties:
            Path: /weather
            Method: GET
      Environment:
        Variables:
          API_KEY: !Ref WeatherApiKey

Parameters:
  WeatherApiKey:
    Type: String
    Description: API key for weather API

Outputs:
  FunctionName:
    Value: !Ref WeatherFunction
    Description: Name of the Lambda function
  ApiUrl:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/"
